//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Little_Beauty_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compras()
        {
            this.Compra_producto = new HashSet<Compra_producto>();
        }
    
        public int id_compra { get; set; }
        public System.DateTime fecha_solicitud { get; set; }
        public int num_confirmacion { get; set; }
        public int total { get; set; }
        public int id_proveedor { get; set; }
        public int num_guia { get; set; }
        public System.DateTime fecha_entrega { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra_producto> Compra_producto { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
