//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Little_Beauty_2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orden()
        {
            this.Orden_producto = new HashSet<Orden_producto>();
        }
    
        public int id_orden { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public int num_confirmacion { get; set; }
        public int total { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<int> id_paquete { get; set; }
        public string direccion { get; set; }
        public Nullable<int> num_guia { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orden_producto> Orden_producto { get; set; }
        public virtual Paquetes Paquetes { get; set; }
    }
}
